name: Busybox

on:
  workflow_call:
    inputs: 
      command:
        type: string
        required: true
    outputs:
      return-message: "cats!"

jobs:
  run-busybox:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ghcr.io/hlesey/busybox:1.36.1
        with:
          entrypoint: ${{ inputs.command }}

