name: Busybox

on:
  workflow_call:
    inputs: 
      command:
        type: string
        required: true
    outputs:
      value: ----------------------------------------

jobs:
  run-busybox:
    runs-on: ubuntu-latest
    steps:
      - uses: ghcr.io/hlesey/busybox:1.36.1
        with:
          entrypoint: ${{ input.command }}

