name: Busybox

on:
  workflow_call:
    inputs: 
      command:
        type: string
        required: true
    outputs:
      return-message: 
        value: "cats!"
      busybox-output:
        value: ${{ jobs.run-busybox.outputs.container-out }}

jobs:
  run-busybox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: "echo hello > ${GITHUB_WORKSPACE}/file1"

      - uses: docker://ghcr.io/linuxcontainers/alpine:latest
        id: busybox
        with:
          args: sh -c scripts/container-script.sh

      - name: out
        run: |
          ls -al
          echo "from host:"
          cat ${GITHUB_WORKSPACE}/file1
          echo "from container:"
          cat ${GITHUB_WORKSPACE}/file3
          echo "from google:"
          cat ${GITHUB_WORKSPACE}/file4

    outputs:
      container-out: ${{ toJSON(steps.busybox.outputs) }}
