name: Busybox

on:
  workflow_call:
    inputs: 
      command:
        type: string
        required: true
    outputs:
      return-message: 
        value: "cats!"
      busybox-output:
        value: ${{ jobs.run-busybox.outputs.container-out }}

jobs:
  run-busybox:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ghcr.io/hlesey/busybox:1.36.1
        id: busybox
        with:
          command: "${{ inputs.command }} > /output/busybox"
          volumes: 
            - "${{ github.workspace }}:/output/"
    outputs:
      container-out: ${{ toJSON(steps.busybox.outputs) }}

