name: Busybox

on:
  workflow_call:
    inputs: 
      command:
        type: string
        required: true
    outputs:
      value: ----------------------------------------

jobs:
  run-busybox:
    runs-on: ubuntu-latest
    steps:
      - uses: registry.hub.docker.com/library/busybox
        with:
          entrypoint: ${{ input.command }}

