name: Busybox

on:
  workflow_call:
    inputs: 
      command:
        type: string
        required: true
    outputs:
      return-message: 
        value: "cats!"
      busybox-output:
        value: ${{ jobs.run-busybox.outputs.container-out }}

jobs:
  run-busybox:
    runs-on: ubuntu-latest
    steps:
      - run: "echo hello > ${GITHUB_WORKSPACE}/file1"

      - uses: docker://ghcr.io/linuxcontainers/alpine:latest
        id: busybox
        with:
          args: 'sh -c "echo cats > ${GITHUB_WORKSPACE}/file3"'

      - name: out
        run: |
          ls -al
          cat ${GITHUB_WORKSPACE}/file1

    outputs:
      container-out: ${{ toJSON(steps.busybox.outputs) }}
