name: Busybox

on:
  workflow_call:
    inputs: 
      command:
        type: string
        required: true
    outputs:
      return-message: 
        value: "cats!"
      busybox-output:
        value: ${{ jobs.run-busybox.outputs.container-out }}

jobs:
  run-busybox:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello" > ${GITHUB_WORKSPACE}/file1
    # - run: echo "input command: ${{ inputs.command }}"
      - uses: docker://ghcr.io/hlesey/busybox:1.36.1
        id: busybox
        with:
          command: "${{ inputs.command }} >> $GITHUB_OUTPUT"
      - name: out
        run: |
          ls -al
          cat ${GITHUB_WORKSPACE}/file1
          # cat $GITHUB_WORKSPACE/out
    outputs:
      container-out: ${{ toJSON(steps.busybox.outputs) }}

