name: Busybox

on:
  workflow_call:
    inputs: 
      command:
        type: string
        required: true
    outputs:
      command-output:
        value: -------------------- command return --------------------

jobs:
  busybox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://busybox
        id: busybox-run
        with:
          args: sh -c scripts/busybox.sh '${{ inputs.command }}'
    outputs:
      command-output: ${{ steps.busybox-run.output.command-output }}
