name: os-release

on:
  workflow_call:
    inputs:
      message:
        type: string
        required: true
    outputs:
      release:
        value: ${{ jobs.release-info.outputs.pretty-name }} 
      altered-message:
        value: ${{ jobs.alter-name.outputs.altered-message }} 

jobs:
  release-info:
    runs-on: ubuntu-latest
    steps:
      - id: get-pretty-name
        shell: bash
        run: |
          release="$(cat /etc/os-release | head -n1)"
          echo "pretty-name=${release}" >> "${GITHUB_OUTPUT}"
    outputs:
      pretty-name: ${{ steps.get-pretty-name.outputs.pretty-name }}

  alter-name:
    runs-on: ubuntu-latest
    steps:
      - id: say-hello
        run: |
          altered="hello ${{ inputs.message }}"
          echo "hello=${altered}" >> "${GITHUB_OUTPUT}"
    outputs:
      altered-message: ${{ steps.say-hello.outputs.hello }}


