name: Push

# bun
on: 
  push:
    
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  long-running:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJSON(github) }}' | jq -M 
          sleep 5000
