run-name: "${{ github.ref_type }}-${{ github.ref_name }}"

on:
  push:

jobs:
  db:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        volumes:
          - /var/run/postgresql:/var/run/postgresql
        options: --name postgres 
        # options: --name postgres --hostname postgres
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: docker container ls -a
      - run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - run: cat sql/fizzbuzz.sql
      # - run: PGPASSWORD=postgres psql -h /var/run/postgresql -U postgres -d postgres -c 'SHOW config_file;'
      - run: |
          PGPASSWORD=postgres psql \
            -h /var/run/postgresql \
            -U postgres \
            -d postgres \
            -f ${GITHUB_WORKSPACE}/sql/fizzbuzz.sql
