run-name: "${{ github.ref_type }}-${{ github.ref_name }}"

on:
  push:

jobs:
  db:
    runs-on: ubuntu-latest
    container:
      image: postgres:16.3
      env:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_HOST_AUTH_METHOD: trust
        POSTGRES_HOST: localhost
      ports:
        - 5432:5432
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo --------------------
          psql -h localhost -c 'SHOW config_file;'
          echo --------------------
