run-name: "${{ github.ref_type }}-${{ github.ref_name }}"

on:
  push:

jobs:
  db:
    runs-on: ubuntu-latest
    container:
      image: postgres
      env:
        POSTGRES_PASSWORD: cat
      # ports:
      #   - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - run: |
          PGPASSWORD=cat psql -U postgres -c 'SHOW config_file;'
