name: Push

on:
  push:
    branches:
      - main

jobs:
  call-other:
    uses: ./.github/workflows/busybox.yaml
    with:
      command: "echo hi"

  echo-output:
    runs-on: ubuntu-latest
    needs: 
      - call-other
    steps:
      - run: |
          echo "echoing: ${{ needs.call-other.outputs.return-message }}"


