name: Push

on:
  push:
    branches:
      - main

jobs:
  call-other:
    uses: ./.github/workflows/busybox.yaml
    with:
      command: "ls -al /"

  echo-output:
    needs: 
      - call-other
    steps:
      - run: |
          echo "echoing: ${{ needs.call-other.outputs.return-message }}"


