run-name: "${{ github.ref_type }}-${{ github.ref_name }}"

on:
  push:

jobs:
  db:
    runs-on: ubuntu-latest
    container:
      image: postgres:16.3
      env:
        PGPASSWORD: cat
        POSTGRES_PASSWORD: cat
      ports:
        - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - run: |
          cat /etc/os-release
          which psql
          echo --------------------
          echo "pg: ${PGPASSWORD}"
          echo "postgres: ${POSTGRES_PASSWORD}"
          echo --------------------
          which psql
          echo --------------------
          # echo "no user"
          psql -h localhost -U postgres -c 'SHOW config_file;'
          # echo --------------------
          # echo "postgres user"
          # psql -U postgres -c 'SHOW config_file;'
          # echo --------------------
