name: On Push
  
on:
  push:
    branches:
      - main

jobs:
  busybox-run:
    uses: ./.github/workflows/busybox.yaml
    with:
      command: wget -O - http://www.google.com
      # command: ls -al

  echo-output:
    runs-on: ubuntu-latest
    needs:
      - busybox-run
    steps:
      - run: echo ${{ needs.busybox-run.outputs.command-output }}
