run-name: "${{ github.ref_type }}-${{ github.ref_name }}"

on:
  push:

jobs:
  db:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          # POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        volumes:
          - /var/run/postgresql:/var/run/postgresql
        # options: --name postgres 
        options: --name postgres --hostname postgres
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: docker container ls -a
      - run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - run: psql --version
      - run: psql --help
      - run: psql -h postgres -p 5432 -c 'SHOW config_file;'
