name: Push

on: 
  push:
    
concurrency:
  group: "${{ github.ref_type}}-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  long-running:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 5000
