name: On push

on:
  push:
    branches:
      - main

jobs:
  call-other:
    uses: ./.github/workflows/os-release.yaml
    with:
      message: utkino

  print-stuff:
    runs-on: ubuntu-latest
    needs: 
      - call-other
    steps:
      - run: |
          echo "os release: ${{ needs.call-other.outputs.release }}"
            echo "altered-message: ${{ needs.call-other.outputs.altered-message }}"


        
